import {
  ArrowLeftRight,
  Baby,
  Banknote,
  Briefcase,
  Bus,
  Car,
  Circle,
  Coffee,
  CreditCard,
  Dog,
  Dumbbell,
  Film,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HeartPulse,
  Home,
  Landmark,
  Laptop,
  type LucideIcon,
  MoreHorizontal,
  Music,
  Palmtree,
  PawPrint,
  Phone,
  Plane,
  Receipt,
  Scissors,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Stethoscope,
  Tag,
  Train,
  TrendingUp,
  Tv,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Wine,
  Wrench,
  Zap,
} from "lucide-react";

export const CATEGORY_ICONS = [
  { name: "UtensilsCrossed", label: "Alimentação", Icon: UtensilsCrossed },
  { name: "Car", label: "Transporte", Icon: Car },
  { name: "Home", label: "Moradia", Icon: Home },
  { name: "HeartPulse", label: "Saúde", Icon: HeartPulse },
  { name: "Gamepad2", label: "Lazer", Icon: Gamepad2 },
  { name: "ShoppingBag", label: "Compras", Icon: ShoppingBag },
  { name: "GraduationCap", label: "Educação", Icon: GraduationCap },
  { name: "Receipt", label: "Contas", Icon: Receipt },
  { name: "Briefcase", label: "Trabalho", Icon: Briefcase },
  { name: "Laptop", label: "Freelance", Icon: Laptop },
  { name: "TrendingUp", label: "Investimentos", Icon: TrendingUp },
  { name: "Gift", label: "Presente", Icon: Gift },
  { name: "Dog", label: "Pets", Icon: Dog },
  { name: "PawPrint", label: "Animais", Icon: PawPrint },
  { name: "Baby", label: "Bebê", Icon: Baby },
  { name: "Banknote", label: "Dinheiro", Icon: Banknote },
  { name: "Wallet", label: "Carteira", Icon: Wallet },
  { name: "CreditCard", label: "Cartão", Icon: CreditCard },
  { name: "Landmark", label: "Banco", Icon: Landmark },
  { name: "ArrowLeftRight", label: "Transferência", Icon: ArrowLeftRight },
  { name: "Bus", label: "Ônibus", Icon: Bus },
  { name: "Train", label: "Trem", Icon: Train },
  { name: "Plane", label: "Viagem", Icon: Plane },
  { name: "Fuel", label: "Combustível", Icon: Fuel },
  { name: "Coffee", label: "Café", Icon: Coffee },
  { name: "Wine", label: "Bebidas", Icon: Wine },
  { name: "Film", label: "Cinema", Icon: Film },
  { name: "Tv", label: "Streaming", Icon: Tv },
  { name: "Music", label: "Música", Icon: Music },
  { name: "Dumbbell", label: "Fitness", Icon: Dumbbell },
  { name: "Stethoscope", label: "Médico", Icon: Stethoscope },
  { name: "Scissors", label: "Beleza", Icon: Scissors },
  { name: "ShoppingCart", label: "Mercado", Icon: ShoppingCart },
  { name: "Smartphone", label: "Celular", Icon: Smartphone },
  { name: "Phone", label: "Telefone", Icon: Phone },
  { name: "Wifi", label: "Internet", Icon: Wifi },
  { name: "Zap", label: "Energia", Icon: Zap },
  { name: "Wrench", label: "Manutenção", Icon: Wrench },
  { name: "Palmtree", label: "Férias", Icon: Palmtree },
  { name: "Sparkles", label: "Extra", Icon: Sparkles },
  { name: "Tag", label: "Geral", Icon: Tag },
  { name: "MoreHorizontal", label: "Outros", Icon: MoreHorizontal },
  { name: "Circle", label: "Padrão", Icon: Circle },
] as const;

export type CategoryIconName = (typeof CATEGORY_ICONS)[number]["name"];

export const CATEGORY_ICON_ALLOWLIST = CATEGORY_ICONS.map((item) => item.name);

const iconMap = new Map<string, LucideIcon>(CATEGORY_ICONS.map((item) => [item.name, item.Icon]));

export function getCategoryIconComponent(name: string): LucideIcon {
  return iconMap.get(name) ?? Circle;
}

export function getCategoryIconLabel(name: string): string {
  return CATEGORY_ICONS.find((item) => item.name === name)?.label ?? name;
}
